[build]
  command = "npm run build"
  environment = {
    FIREBASE_API_KEY = "${env:REACT_APP_FIREBASE_API_KEY}"
    FIREBASE_AUTH_DOMAIN = "${env:REACT_APP_FIREBASE_AUTH_DOMAIN}"
    FIREBASE_PROJECT_ID = "${env:REACT_APP_FIREBASE_PROJECT_ID}"
    FIREBASE_STORAGE_BUCKET = "${env:REACT_APP_FIREBASE_STORAGE_BUCKET}"
    FIREBASE_MESSAGING_SENDER_ID = "${env:REACT_APP_FIREBASE_MESSAGING_SENDER_ID}"
    FIREBASE_APP_ID = "${env:REACT_APP_FIREBASE_APP_ID}"
    FIREBASE_MEASUREMENT_ID = "${env:REACT_APP_FIREBASE_MEASUREMENT_ID}"
}
